# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-OrlLLJ7gqjfIesot3C8jgmNYetmh4j
"""

import pandas as pd

def sentimentProportion(airlineName, sentimentType):
    # Read the CSV file into a DataFrame
    myFilePath = "Airline-Sentiment.csv"
    myData = pd.read_csv(myFilePath, encoding='latin1')

    # Filter the data for the specified airline and retweet_count condition
    myNewData = myData[(myData['airline'] == airlineName) & (myData['retweet_count'] > 1)]

    # Calculate the proportion of the specified sentiment type
    total_tweets = len(myNewData)
    sentiment_tweets = len(myNewData[myNewData['airline_sentiment'] == sentimentType])

    # Check if there are tweets before calculating the proportion
    if total_tweets > 0:
        proportion = sentiment_tweets / total_tweets
    else:
        proportion = 0.0  # Set proportion to 0 if there are no tweets

    return proportion